// Data-driven levels. To add a level: append an object here (no engine changes needed).
//
// Map legend:  # wall   . floor   F furniture (blocks move + sight)   H hiding spot   S start   E exit
//              L loot (+10)   R rare loot (+50)   K key   D locked door (needs a key)   A alarm zone
// Coordinates in guards/cameras/lasers are tile (x, y) with (0,0) top-left. Angles are degrees: 0=east, 90=south.
//
// guards:  { patrol:[[x,y,waitSeconds?],...], mode:'loop'|'pingpong', face, speed, range, fov, sweep:{amp,speed} }
// cameras: { x, y (wall tile), angle, arc, speed, range, fov }
// lasers:  { x, y, dir:'h'|'v', len, on, off, phase }
export const LEVELS = [
  { level: 1, world: 'house', name: 'First Night', difficulty: 1,
    hint: 'Tap where you want the thief to go. Grab the loot, then reach the green exit.',
    map: [
      '#########',
      '#S......#',
      '#.###.#.#',
      '#.#L#.#L#',
      '#.#.#.#.#',
      '#...#...#',
      '#.#####.#',
      '#L.....E#',
      '#########',
    ] },
  { level: 2, world: 'house', name: 'Night Watch', difficulty: 1,
    hint: 'Guards see in a cone. Stay out of it — time your moves.',
    map: [
      '#########',
      '#S......#',
      '#..F.F..#',
      '#L.....L#',
      '#..F.F..#',
      '#.......#',
      '####.####',
      '#E.....L#',
      '#########',
    ],
    guards: [{ patrol: [[2, 3, 1], [6, 3, 1]], mode: 'pingpong', speed: 1.5, range: 4 }] },
  { level: 3, world: 'house', name: 'Hide & Seek', difficulty: 2,
    hint: 'Step onto a wardrobe or bush to hide. Hidden thieves cannot be seen.',
    map: [
      '#########',
      '#L..H..L#',
      '#.##.##.#',
      '#.#...#.#',
      '#.#.R.#.#',
      '#.#...#.#',
      '#.##.##.#',
      '#S..H..E#',
      '#########',
    ],
    guards: [{ patrol: [[1, 1], [7, 1], [7, 7], [1, 7]], mode: 'loop', speed: 1.5, range: 4.5 }] },
  { level: 4, world: 'house', name: 'Double Shift', difficulty: 3,
    map: [
      '#########',
      '#L.F.F.L#',
      '#.......#',
      '#.F...F.#',
      '#.......#',
      '###.#.###',
      '#.......#',
      '#.F.R.F.#',
      '#.......#',
      '#S.....E#',
      '#########',
    ],
    guards: [
      { patrol: [[1, 2, 0.8], [7, 2, 0.8]], mode: 'pingpong', speed: 1.6 },
      { patrol: [[7, 6, 0.8], [1, 6, 0.8]], mode: 'pingpong', speed: 1.6 },
    ] },
  { level: 5, world: 'house', name: 'Vault Room', difficulty: 3,
    hint: 'A guard who stares in one place sweeps left and right — watch the rhythm.',
    map: [
      '#########',
      '#S.....L#',
      '#.#####.#',
      '#.#L.R#.#',
      '#.#...#.#',
      '#.##.##.#',
      '#...H...#',
      '#.#####.#',
      '#L.....E#',
      '#########',
    ],
    guards: [
      { patrol: [[2, 6]], face: 0, sweep: { amp: 35, speed: 1.4 }, range: 4, fov: 60 },
      { patrol: [[1, 8, 0.5], [7, 8, 0.5]], mode: 'pingpong', speed: 1.5 },
    ] },
  { level: 6, world: 'house', name: 'Eyes on the Wall', difficulty: 4,
    hint: 'CCTV cameras sweep. If one sees you it sounds the alarm and guards rush in.',
    map: [
      '#########',
      '#S......#',
      '#.FF.FF.#',
      '#.......#',
      '#L.F.F.L#',
      '#.......#',
      '#.FF.FF.#',
      '#H.....E#',
      '#########',
    ],
    cameras: [{ x: 4, y: 0, angle: 90, arc: 45, speed: 26, range: 6, fov: 44 }],
    guards: [{ patrol: [[1, 5, 0.8], [7, 5, 0.8]], mode: 'pingpong', speed: 1.4 }] },
  { level: 7, world: 'house', name: 'Locked In', difficulty: 4,
    hint: 'Grab the key to open the locked door. Each key opens one door.',
    map: [
      '#########',
      '#S.....K#',
      '#.F...F.#',
      '#.......#',
      '####D####',
      '#L.R.L..#',
      '#.......#',
      '#E.F.F.H#',
      '#########',
    ],
    guards: [
      { patrol: [[1, 3, 1], [7, 3, 1]], mode: 'pingpong', speed: 1.5 },
      { patrol: [[7, 6, 1], [1, 6, 1]], mode: 'pingpong', speed: 1.5 },
    ] },
  { level: 8, world: 'house', name: 'Tripwire', difficulty: 5,
    hint: 'Red alarm tiles set off the alarm. Walk around them.',
    map: [
      '#########',
      '#S.....L#',
      '#.AAAA..#',
      '#.......#',
      '#.F.H.F.#',
      '#.AAAA..#',
      '#.......#',
      '#L.....E#',
      '#########',
    ],
    guards: [
      { patrol: [[1, 3, 0.8], [7, 3, 0.8]], mode: 'pingpong', speed: 1.5 },
      { patrol: [[7, 6, 0.8], [1, 6, 0.8]], mode: 'pingpong', speed: 1.5 },
    ] },
  { level: 9, world: 'house', name: 'Inside Job', difficulty: 6,
    map: [
      '#########',
      '#S..F..K#',
      '#.F....L#',
      '#.##D##.#',
      '#.#...#.#',
      '#.#.R.#.#',
      '#.#...#.#',
      '#.#####.#',
      '#L.....E#',
      '#########',
    ],
    cameras: [{ x: 0, y: 2, angle: 0, arc: 40, speed: 24, range: 6, fov: 40 }],
    guards: [{ patrol: [[1, 4, 0.6], [1, 8, 0.6], [7, 8, 0.6], [7, 4, 0.6]], mode: 'loop', speed: 1.6 }] },
  { level: 10, world: 'house', name: 'The Big Score', difficulty: 7,
    hint: 'Everything at once. Lasers blink — cross when they are off.',
    map: [
      '#########',
      '#S.F...K#',
      '#...H...#',
      '#.F...F.#',
      '###A.A###',
      '#L.....L#',
      '#.F.H.F.#',
      '#.......#',
      '####D####',
      '#R.....L#',
      '#.......#',
      '#E.....L#',
      '#########',
    ],
    lasers: [{ x: 1, y: 10, dir: 'h', len: 7, on: 1.2, off: 1.8 }],
    cameras: [{ x: 8, y: 9, angle: 180, arc: 30, speed: 22, range: 6, fov: 40 }],
    guards: [
      { patrol: [[7, 2, 0.8], [1, 2, 0.8]], mode: 'pingpong', speed: 1.5 },
      { patrol: [[7, 6, 0.8], [1, 6, 0.8]], mode: 'pingpong', speed: 1.6 },
    ] },
];

export const PLAYABLE_LEVELS = LEVELS.length;
export const getLevel = (n) => LEVELS.find((l) => l.level === n) || null;

/** The compact "summary" form from the design doc, derived from the full definition. */
export function summarize(def) {
  const count = (c) => def.map.reduce((a, r) => a + [...r].filter((x) => x === c).length, 0);
  return { level: def.level, world: def.world, guards: (def.guards || []).length, cameras: (def.cameras || []).length,
    loot: count('L') + count('R'), keys: count('K'), difficulty: def.difficulty };
}
